Parametrize values
Tinker-Ware/static-page-s3-bucket pull request #3
Opened 2019-09-13 17:56 UTC by estradag

Closes #2 

- Modified the Ansible part of the project to give it the structure of an Ansible role. It will be taken out to its own repo in a future update.
- Parametrized static page repository and the bucket/domain that should be used to access the page once it has been uploaded to the corresponding S3 bucket.
- `www` subdomain S3 bucket and Route53 record are optional.

2019-09-13 18:10 UTC, cracos approved these changes
LTMG, don't forget in the future apply enhancements

2019-09-13 21:37 UTC, AAlvz requested changes
I just added requests for small changes and a couple of questions :)

2019-09-13 21:37 UTC, AAlvz commented on ansible-s3-static-page-upload-role/defaults/main.yml
> +bucket_name: tinkerware.io
missing end of line :(

2019-09-13 21:37 UTC, AAlvz commented on ansible-s3-static-page-upload-role/vars/main.yml
> +# bucket_name: tinkerware.io
missing end of line. 
Why are the lines commented? I don't think there's a need 🤔

2019-09-13 21:37 UTC, AAlvz commented on main.yml
> +    - { role: ansible-s3-static-page-upload-role }
missing end of line

2019-09-13 21:37 UTC, AAlvz commented on variables.tf
> +}
missing end of line

2019-09-13 21:37 UTC, AAlvz commented on main.tf
> +  count = "${ var.create_www_bucket ? 1 : 0 }"
why are we counting?

2019-09-25 21:37 UTC, estradag commented on main.tf
> +  count = "${ var.create_www_bucket ? 1 : 0 }"
(Kind of) validation to create or not the resource if the bucket for the `www` subdomain is required

2019-09-25 21:38 UTC, estradag commented on ansible-s3-static-page-upload-role/vars/main.yml
> +# bucket_name: tinkerware.io
@cracos suggestion, so there's no need to look inside `defaults` folder to see the variables set there.

2019-09-25 22:03 UTC, AAlvz commented on ansible-s3-static-page-upload-role/vars/main.yml
> +# bucket_name: tinkerware.io
the default variables exist for the cases when you don't want to change anything or look at the code and just "make this thing run" . That's why they should exist. To take the default ones if no other variables are defined and avoid failures.

2019-09-25 22:05 UTC, AAlvz commented on main.tf
> +  count = "${ var.create_www_bucket ? 1 : 0 }"
then should we change the name of that value? from `count` to something like `create_bucket` (True: 1, False: 0)

2019-09-25 22:09 UTC, estradag commented on main.tf
> +  count = "${ var.create_www_bucket ? 1 : 0 }"
`count` is a reserved word in Terraform, that's why the ternary operator only gives the values `1` and `0`, to create or not, respectively the bucket for that subdomain.

The variable `create_www_bucket` is the boolean used to trigger the ternary conditional.

2019-09-25 22:25 UTC, AAlvz commented on main.tf
> +  count = "${ var.create_www_bucket ? 1 : 0 }"
Ah true D:

2019-09-25 22:31 UTC, AAlvz commented on ansible-s3-static-page-upload-role/vars/main.yml
> +# bucket_name: tinkerware.io
I was looking at the wrong file. Everything seems fine. Move on

2019-09-25 22:31 UTC, AAlvz approved these changes
LGTM

2019-09-25 22:32 UTC, merged